# Action is for moving the the pump at a specific flow rate for a specific time

# Goal definition
float32 flow_rate # In uL/ min
int8 ratio # Ratio to pump A to pump B, 0-100
int16 time # Time in seconds 

---
# Result definition
bool success

---
# Feedback
int32 time_remaining # Time remaining in seconds
