
# Constants
uint8 FILL = 0 # Increase the volume of the pump
uint8 EMPTY = 1 # Decrease the volume of the pump

# Goal
uint8 direction # Direction of the pump 
uint8 torque # Torque of the pump

---
# Result
uint8 status # Status of the pump

---
# Feedback
