# PumpVoidRemoval.action
# Interface for removing and disolving gas in the pumps
# Will pump into blocked position and then empty into respective solvents at oressure

# Goal definition
uint8 maximum_percent_displaced # Valid range 0 - 100%
uint16 target_pressure # In PSI

---
# Result definition
bool success

---
# Feedback definition
uint16[] pressure_differential # Distance to target pressure in PSI, index 0 is pump 1, index 1 is pump 2